name: Publish sa-assembly build logic

on:
  workflow_dispatch:
  push:
    branches: [ main ] # Trigger on pushes to the main branch

jobs:
  publish:
    name: Release sa-assembly
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # Leverage caching for faster builds

      - name: Checkout
        uses: actions/checkout@v3  # Checkout the code

      - name: Grant permission for gradlew to execute
        run: chmod +x gradlew

      - name: Build with Gradle sa-assembly
        run: ./gradlew assemble  # Build your build logic

      - name: Publish to GitHub Packages
        run: ./gradlew publish  # Publish to GitHub Packages

        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}