name: Publish sa-assembly build logic

on:
  workflow_dispatch:
  push:
    branches: [ main ] # Trigger on pushes to the main branch

jobs:
  publish:
    name: Release sa-assembly
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Checkout the code

      - name: List Files
        run: ls -la

      - name: Grant permission for gradlew to execute
        run: chmod +x gradlew

      - name: Check gradlew permissions
        run: ls -l gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # Leverage caching for faster builds

      - name: Build with Gradle (sa-assembly)
        run: ./gradlew build --no-daemon

      - name: Assemble sa-assembly
        run: ./gradlew :assembly:assemble  # Build your build logic

      - name: Publish to GitHub Packages
        run: ./gradlew :assembly:publish  # Publish to GitHub Packages

        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}