name: Publish sa-assembly build logic

on:
  workflow_dispatch:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
  release:
    types: [ created ] # Trigger on new release creation

jobs:
  publish:
    name: Release sa-assembly
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout
      - uses: actions/checkout@v3  # Checkout the code

      - name: Cache gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant permission for gradlew to execute
        run: chmod +x gradlew

      - name: Build with Gradle
        run: bash ./gradlew assemble  # Build your build logic

      - name: Publish to GitHub Packages
        run: bash ./gradlew publish  # Publish to GitHub Packages

        env:
          GITHUB_ACTOR: ${{ secrets.ACTOR }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}